app = "options-bot"
primary_region = "sin"

[build]

[env]
  TZ = "Asia/Singapore"

[processes]
  app = "python main.py"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[services.ports]]
    handlers = ["http"]
    port = 80
