app = "options-bot"
primary_region = "sin"

[build]

[env]
  TZ = "Asia/Singapore"
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"

[processes]
  app = "python main.py"

[deploy]
  strategy = "immediate"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
