app = "options-bot"
primary_region = "sin"

[build]

[env]
  TZ = "Asia/Singapore"

[processes]
  app = "python main.py"

[machines]
  auto_stop = false

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  strategy = "immediate"
  max_unavailable = 1
